---
- name:  Backup all configs locally on the device
  hosts: all
  vars:
    savedfile: '{{ ansible_hostname }}_{{ ansible_date_time.date }}.conf'
  
  tasks:
  - name: Enter config mode - save config
    picos_config: mode='cli_config' cmd='save {{ ansible_hostname }}_{{ ansible_date_time.date }}.conf'
    register: exec_result
  - name: Saved Configuration
    shell: cat {{ savedfile }}
    register: savedfile_contents

  - name: Save output to ampcon directory
    copy:
      content: "{{ savedfile_contents.stdout | replace('\\n', '\n') }}"
      dest: "/home/admin/{{ ansible_hostname }}_{{ ansible_date_time.date }}_RESTORE.conf"
    delegate_to: localhost

  - name: Enter config mode - running config
    picos_config: mode='cli_show' cmd='show running-config | display set | no-more'
    register: config

  - name: Saved Configuration
    debug: var=config.stdout_lines
    register: config.stdout_lines
    
  - name: Save SET output to ampcon directory
    copy:
      content: "{{ config.stdout | replace('\\n', '\n') }}"
      dest: "/home/admin/{{ ansible_hostname }}_{{ ansible_date_time.date }}_SET.conf"
    delegate_to: localhost