---
- name:  Find which port in the network a MAC Address is on
  hosts: all
  vars:
    ipregexp: 'value=\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/\d{1,3}\s*^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$'
    intfregexp: 'value=\w\w\-\d/\d/\d*'   
  tasks:
  - name: Get MAC for a given IP Address 
    picos_config: mode='cli_show' cmd='show arp | match {{IPAddr}} '
    register: arphunt_result
  - name: Show execution result
    debug: var=arphunt_result.stdout_lines
  - name: Get MAC for a given IP Address check VXLANs 
    picos_config: mode='cli_show' cmd='show vxlan arp | match {{IPAddr}} '
    register: vxlanarp_result
  - name: Show execution result
    debug: var=vxlanarp_result.stdout_lines
  - name: Get MAC for a given IP Address check VXLANs 
    picos_config: mode='cli_show' cmd='show vxlan address-table | match {{MacAddr}} '
    register: vxlanmac_result
  - set_fact:
        arpvalue: "{{ vxlanmac_result.stdout_lines | regex_search(intfregexp,'\\1') | first }}"
  - name: Show vxlanmac_execution result
    debug: var=vxlanmac_result.stdout_lines
  - name: Show vxlanmac_regex_execution result
    debug: var=arpvalue   
  - name: Get switch port for a given Mac Address 
    picos_config: mode='cli_show' cmd='show mac-address table | match {{MacAddr}} '
    register: mactab_result
  - name: Show execution result
    debug: var=mactab_result.stdout_lines          